# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3947299b373d9a98023191150f8397f9caffe9f403eb442ca092755dcd938e41f542b1a77023764b008716847a9b3931c2c6ab0fa03340ac3f2c07bd937bece

test:
  secret_key_base: 05463b64e784c6eba5fd192a99c2f32fecc0dea9ef535e51e230dde7123e376bd3294ff416cae996642e5b7472e42f0096aadb05ec0de2c1cc03f25775e1266d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
